name: java_inside_out_tdd

services:
  exercises:
    build: .
    volumes:
      - ./src:/inside_out_tdd/src
      - ./build.gradle:/inside_out_tdd/build.gradle
      - ./wordle-cheat :/inside_out_tdd/wordle-cheat
    working_dir: /inside_out_tdd
    tty: true
    command:
      - -lc
      - |
        echo 'trap "echo ‼️ You just quit the exercises terminal.; echo To get it back run: docker compose run exercises" EXIT' >> /root/.bashrc
        echo "To run the tests:"
        echo "  gradle test"
        echo "Or for watch mode:"
        echo "  gradle test --continuous"
        exec /bin/bash -l
