services:
  exercises:
    build: .
    volumes:
      - ./src:/failing_well/src
      - ./build.gradle:/failing_well/build.gradle
      - ./gradle.properties:/failing_well/gradle.properties
    working_dir: /failing_well
    tty: true
    command:
      - -lc
      - |
        echo 'trap "echo ‼️ You just quit the exercises terminal.; echo To get it back run: docker compose run exercises" EXIT' >> /root/.bashrc
        echo "To run the tests:"
        echo "  gradle test"
        echo "Or for watch mode:"
        echo "  gradle test --continuous"
        exec /bin/bash -l
  tests:
    build: .
    volumes:
      - ./src:/failing_well/src
      - ./build.gradle:/failing_well/build.gradle
      - ./gradle.properties:/failing_well/gradle.properties
    working_dir: /failing_well
    command:
      - -c
      - gradle test --continuous --console=rich --warning-mode none
