services:
  exercises:
    build: .
    volumes:
      - ./src:/<EXERCISE_DIR>/src
      - ./build.gradle:/<EXERCISE_DIR>/build.gradle
      - ./gradle.properties:/<EXERCISE_DIR>/gradle.properties
      - ./scripts:/<EXERCISE_DIR>/scripts
    working_dir: /<EXERCISE_DIR>
    tty: true
    command:
      - -lc
      - |
        echo 'trap "echo ‼️ You just quit the exercises terminal.; echo To get it back run: docker compose run exercises" EXIT' >> /root/.bashrc
        echo "To run the tests:"
        echo "  gradle test"
        echo "Or for watch mode:"
        echo "  gradle test --continuous"
        exec /bin/bash -l
  tests:
    build: .
    volumes:
      - ./src:/<EXERCISE_DIR>/src
      - ./build.gradle:/<EXERCISE_DIR>/build.gradle
      - ./gradle.properties:/<EXERCISE_DIR>/gradle.properties
      - ./scripts:/<EXERCISE_DIR>/scripts
    working_dir: /<EXERCISE_DIR>
    command:
      - -c
      - gradle test --continuous --console=rich --warning-mode none
